[tool.poetry]
name = "google_home"
version = "0.0.0"
description = "Home Assistant Google Home community integration"
authors = ["Ilja Leiko <leikoilja@gmail.com"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
zeroconf = "^0.28.8"
homeassistant = "^2021.3.2"
glocaltokens = "0.2.7"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
pre-commit = "^2.10.1"
pylint = "^2.7.2"
isort = "^5.7.0"
mypy = "^0.812"

[tool.pylint.messages_control]
# Reasons disabled:
# too-many-* - not enforced for the sake of readability
# too-few-* - same as too-many-*
disable = [
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-instance-attributes",
]

[tool.pylint.format]
max-line-length = 88

[tool.isort]
profile = "black"
force_sort_within_sections = true
combine_as_imports = true
known_first_party = [
    "homeassistant",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
