[tool.poetry]
name = "google_home"
version = "0.0.0"
description = "Home Assistant Google Home community integration"
authors = ["Ilja Leiko <leikoilja@gmail.com"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
zeroconf = "^0.28.8"
glocaltokens = "^0.2.4"
homeassistant = "^2021.3.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
reorder-python-imports = "^2.4.0"
pre-commit = "^2.10.1"
pylint = "^2.7.2"

[tool.pylint.messages_control]
disable = [
    "broad-except",
    "invalid-name",
    "line-too-long",
    "logging-format-interpolation",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "no-else-return",
    "no-member",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-instance-attributes",
    "unused-argument",
    "unused-import",
]

[tool.pylint.format]
max-line-length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
