[tool.poetry]
name = "google-home"
version = "0.0.0"
description = "Home Assistant Google Home community integration"
authors = ["Ilja Leiko <leikoilja@gmail.com"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
reorder-python-imports = "^2.4.0"
pre-commit = "^2.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
